name: things i like
favicon: null
layout_spectrum: 0.6951931600924581
typography_spectrum: 0.3952068714424968
title: Simpl
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffcdd'
    - '#56c2cc'
    - '#160300'
    - '#df2f00'
    - '#714c31'
  brandStrength: 0.5
  lightness: 0.23916513053700328
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
